# Generated by Django 3.0.8 on 2020-07-25 19:05

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import interactions.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalAverages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openness', django.contrib.postgres.fields.jsonb.JSONField(editable=False)),
                ('conscientiousness', django.contrib.postgres.fields.jsonb.JSONField(editable=False)),
                ('extraversion', django.contrib.postgres.fields.jsonb.JSONField(editable=False)),
                ('agreeableness', django.contrib.postgres.fields.jsonb.JSONField(editable=False)),
                ('neuroticism', django.contrib.postgres.fields.jsonb.JSONField(editable=False)),
                ('calculated_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'get_latest_by': 'calculated_on',
            },
        ),
        migrations.CreateModel(
            name='SelfAnswerGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_date_and_time', models.DateTimeField(auto_now_add=True)),
                ('answers', django.contrib.postgres.fields.jsonb.JSONField(editable=False)),
                ('accuracy', models.FloatField(blank=True, editable=False, null=True, validators=[interactions.validators.percentage_validator])),
                ('scores', django.contrib.postgres.fields.jsonb.JSONField(editable=False)),
                ('self_user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selfanswergroup_self', to='users.UserProfile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RelationAnswerGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_date_and_time', models.DateTimeField(auto_now_add=True)),
                ('answers', django.contrib.postgres.fields.jsonb.JSONField(editable=False)),
                ('accuracy', models.FloatField(blank=True, editable=False, null=True, validators=[interactions.validators.percentage_validator])),
                ('scores', django.contrib.postgres.fields.jsonb.JSONField(editable=False)),
                ('attempted_against', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationanswergroup_attempted', to='interactions.SelfAnswerGroup')),
                ('relation_user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationanswergroup_relation', to='users.UserProfile')),
                ('self_user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationanswergroup_self', to='users.UserProfile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
