# Generated by Django 3.1a1 on 2020-07-20 14:28

from django.db import migrations, models
import django.db.models.deletion
import interactions.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalAverages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openness', models.JSONField(editable=False)),
                ('conscientiousness', models.JSONField(editable=False)),
                ('extraversion', models.JSONField(editable=False)),
                ('agreeableness', models.JSONField(editable=False)),
                ('neuroticism', models.JSONField(editable=False)),
                ('calculated_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'get_latest_by': 'calculated_on',
            },
        ),
        migrations.CreateModel(
            name='SelfAnswerGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_date_and_time', models.DateTimeField(auto_now_add=True)),
                ('answers', models.JSONField(editable=False, validators=[interactions.validators.json_validator])),
                ('accuracy', models.FloatField(blank=True, editable=False, null=True, validators=[interactions.validators.percentage_validator])),
                ('scores', models.JSONField(editable=False)),
                ('self_user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selfanswergroup_self', to='users.userprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RelationAnswerGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_date_and_time', models.DateTimeField(auto_now_add=True)),
                ('answers', models.JSONField(editable=False, validators=[interactions.validators.json_validator])),
                ('accuracy', models.FloatField(blank=True, editable=False, null=True, validators=[interactions.validators.percentage_validator])),
                ('scores', models.JSONField(editable=False)),
                ('attempted_against', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationanswergroup_attempted', to='interactions.selfanswergroup')),
                ('relation_user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationanswergroup_relation', to='users.userprofile')),
                ('self_user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationanswergroup_self', to='users.userprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
