# Generated by Django 3.1a1 on 2020-07-20 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relationanswergroup',
            name='answers',
            field=models.JSONField(editable=False),
        ),
        migrations.AlterField(
            model_name='selfanswergroup',
            name='answers',
            field=models.JSONField(editable=False),
        ),
    ]
